/**
 * Standalone-embed build target (comms plan §8, §6.2).
 *
 * A blog article that reports on a browser-based demonstrator should let the
 * reader *operate* the thing, not read a description of it (comms plan §6). This
 * script produces self-contained, client-side embeds of the demonstrator's
 * actual components for mounting into articles.
 *
 * HONESTY — this is the load-bearing bit. The embed is not a re-implementation
 * of the component in browser JS; that would be an "illustrative widget" at best
 * and a lie at worst (§6.2 rule 1). Instead we import the *real* component
 * function and pre-render every reachable state at build time over real Meridian
 * fixtures (SPEC-04). The reader's control swaps between outputs the shipped
 * `bandPill` actually produced. The interaction is real; the pixels are the
 * component's own. That earns the "live component — the demonstrator's actual
 * code" label (§6.2 rule 1) without a transpile step or a second copy of the
 * rule to drift out of sync.
 *
 * Output is committed under docs/blog/embeds/<component>/ (like the gallery), so
 * it is reviewable in the repo and copied verbatim into the published site by
 * build-site.ts. Regenerate with `npm run embeds`. Embeds freeze at publication
 * (§6.2 rule 6): an article's copy is a dated snapshot; regeneration is for the
 * embed still being authored, not for silently upgrading shipped articles.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { bandPill } from '../src/components/bandPill.js';
import type { Band, KnowledgeObject } from '../src/generated/types.js';

const root = new URL('../', import.meta.url);

const knowledge = JSON.parse(
  readFileSync(fileURLToPath(new URL('fixtures/knowledge.json', root)), 'utf8'),
) as KnowledgeObject[];

const bandOf = (id: string): Band => {
  const k = knowledge.find((o) => o.logical_id === id);
  const a = k?.answer;
  if (!a || typeof a.lo !== 'number' || typeof a.hi !== 'number') {
    throw new Error(`fixture ${id} has no band answer`);
  }
  return { lo: a.lo, hi: a.hi, unit: a.unit };
};

// Two real Meridian anchors that carry the band pill's whole honesty story:
//   K2 — causeway capacity, source_class=assessed → always banded (amber).
//   K1 — controlling depth, source_class=observed  → fact, may render as a
//        degenerate band unbanded (DEC-14), shown teal for contrast.
const k2 = bandOf('K2'); // [20, 40] tonnes, assessed
const k1 = bandOf('K1'); // [7.5, 7.5] m, observed fact

// A stable track so the band visibly grows/shrinks in place as the reader drags.
const centre = (k2.lo + k2.hi) / 2; // 30 — a layout anchor only; never stored, never a claim (DEC-15)
const maxHalf = (k2.hi - k2.lo) / 2; // 10
const track = { trackLo: centre - maxHalf - 6, trackHi: centre + maxHalf + 6 };

// Pre-render one frame per half-width step with the REAL component. Frame 0 is
// the degenerate (scalar) case — the false precision the discipline refuses.
const frames = Array.from({ length: maxHalf + 1 }, (_, half) => {
  const band: Band = { lo: centre - half, hi: centre + half, unit: k2.unit };
  return {
    half,
    lo: band.lo,
    hi: band.hi,
    html: bandPill(band, { ...track, label: 'K2 causeway capacity' }),
  };
});

const observed = bandPill(k1, { label: 'K1 controlling depth' });

const page = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-embeds.ts — do not edit by hand; run \`npm run embeds\`.
     Self-contained standalone embed of the SPEC-14 band pill (comms plan §8).
     The pill markup below is the shipped src/components/bandPill.ts output over
     real Meridian fixtures (K1/K2); only the slider chrome is embed-local. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Band pill — live component embed</title>
<style>
  :root { color-scheme: light dark; --ink:#1B2732; --muted:#5B6B77; --line:#D8DFE4;
    --panel:#FCFDFD; --band-ink:#9A6A14; --robust-ink:#14655F;
    --sans:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
  @media (prefers-color-scheme: dark){ :root{ --ink:#E7ECF0; --muted:#93A2AE;
    --line:#2A3945; --panel:#17212A; --band-ink:#E0B457; --robust-ink:#63C3B6; } }
  * { box-sizing:border-box; }
  body { margin:0; font-family:var(--sans); color:var(--ink); background:transparent;
    font-size:15px; line-height:1.55; }
  .embed { border:1px solid var(--line); border-radius:12px; background:var(--panel);
    padding:18px 20px; max-width:560px; }
  .tag { font-family:var(--mono); font-size:10.5px; letter-spacing:.06em;
    text-transform:uppercase; color:var(--robust-ink); }
  .stage { min-height:52px; display:flex; align-items:center; margin:14px 0 6px; }
  label.ctl { display:block; font-size:13px; color:var(--muted); margin:14px 0 4px; }
  input[type=range]{ width:100%; accent-color:var(--band-ink); }
  .read { font-family:var(--mono); font-size:12.5px; color:var(--ink); margin-top:8px; min-height:20px; }
  .read b { color:var(--band-ink); }
  .read.scalar b { color:var(--robust-ink); }
  .divider { border:0; border-top:1px solid var(--line); margin:18px 0 14px; }
  .obs { font-size:13px; color:var(--muted); }
  .obs .row { margin-top:8px; }
</style>
</head>
<body>
<div class="embed">
  <div class="tag">live component — the demonstrator's actual code</div>
  <div class="stage" id="stage">${frames[frames.length - 1]!.html}</div>
  <label class="ctl" for="w">Drag: how much does the source actually support?</label>
  <input type="range" id="w" min="0" max="${maxHalf}" value="${maxHalf}" step="1">
  <div class="read" id="read"></div>
  <hr class="divider">
  <div class="obs">
    A directly-observed fact (source class <code>observed</code>) may render unbanded —
    it is a degenerate band, shown teal, not an assessment (DEC-14):
    <div class="row">${observed}</div>
  </div>
</div>
<script>
  // The real bandPill output for each reachable state, pre-rendered at build time.
  var FRAMES = ${JSON.stringify(frames)};
  var stage = document.getElementById('stage');
  var read = document.getElementById('read');
  var slider = document.getElementById('w');
  function render(){
    var f = FRAMES[Number(slider.value)];
    stage.innerHTML = f.html;
    if (f.half === 0){
      read.className = 'read scalar';
      read.innerHTML = '<b>' + f.lo + ' tonnes</b> — a single number. The assessment cannot support this precision: it is exactly the false confidence the band pill refuses.';
    } else {
      read.className = 'read';
      read.innerHTML = 'assessed band <b>' + f.lo + '–' + f.hi + ' tonnes</b> — honest about what is and is not known. No midpoint is stored or shown (DEC-15).';
    }
  }
  slider.addEventListener('input', render);
  render();
</script>
</body>
</html>
`;

const outDir = new URL('docs/blog/embeds/band-pill/', root);
mkdirSync(fileURLToPath(outDir), { recursive: true });
writeFileSync(fileURLToPath(new URL('index.html', outDir)), page);
console.log('wrote docs/blog/embeds/band-pill/index.html');
