/**
 * SPEC-14 — fixture-backed component gallery (start).
 *
 * Renders the band pill and provenance chip — the demonstrator's signature
 * components — over the real Meridian fixture objects (SPEC-04). No compute
 * is faked: this is projection of content-addressable fixture data, which
 * is why it may exist before any service does (delivery plan §2.2).
 *
 * Output: docs/assets/gallery/index.html (committed so the comms site can
 * embed it; regenerate with `npm run gallery` — the header marks it
 * generated).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { bandPill } from '../src/components/bandPill.js';
import { provenanceChip } from '../src/components/provenanceChip.js';
import type { KnowledgeObject } from '../src/generated/types.js';

const knowledge = JSON.parse(
  readFileSync(new URL('../fixtures/knowledge.json', import.meta.url), 'utf8'),
) as KnowledgeObject[];

const esc = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const rows = knowledge
  .map((k) => {
    const answer = k.answer
      ? bandPill(k.answer)
      : `<span style="font-family:ui-monospace,monospace;font-size:11px;color:#3E5D8A;background:#E6ECF6;border:1px solid #C8D5EA;border-radius:3px;padding:2px 7px">open question — ranked for collection</span>`;
    const prov = k.provenance ? provenanceChip(k.provenance) : '';
    const status = `<span style="font-family:ui-monospace,monospace;font-size:10px;color:#5B6B77">${k.logical_id} · v${k.version} · ${k.status}</span>`;
    return `<div style="border:1px solid #D8DFE4;border-radius:6px;padding:12px 14px;margin-bottom:10px;background:#FCFDFD">
  ${status}
  <div style="font-weight:600;font-size:13.5px;margin:3px 0 8px">${esc(k.question)}</div>
  <div style="margin-bottom:6px">${answer}</div>
  <div>${prov}</div>
</div>`;
  })
  .join('\n');

const html = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-gallery.ts (npm run gallery) — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ASSAY — component gallery (SPEC-14)</title>
</head>
<body style="margin:0;background:#EDF0F2;color:#1B2732;font-family:system-ui,sans-serif;font-size:14px;line-height:1.5">
<div style="max-width:820px;margin:0 auto;padding:28px 24px 64px">
<h1 style="font-size:24px;border-bottom:3px solid #1B2732;padding-bottom:12px">ASSAY component gallery</h1>
<p style="font-size:12.5px;color:#5B6B77"><b>Live components — the demonstrator's actual code</b>, rendered over Meridian vignette fixture data (SPEC-04). Components, not product: no service, no compute, no plan exists behind this page. Every assessed value is banded with provenance welded on (ASSAY-DEC-9); the Meridian scenario is engineered fiction (ASSAY-DEC-8).</p>
<h2 style="font-size:16px;margin-top:28px">The knowledge base, K1–K14</h2>
${rows}
<p style="font-size:11.5px;color:#5B6B77;margin-top:28px">Generated from <code>fixtures/knowledge.json</code> by <code>npm run gallery</code> · identifiers frozen per assay-vignette.md §8</p>
</div>
</body>
</html>
`;

mkdirSync(new URL('../docs/assets/gallery/', import.meta.url), { recursive: true });
writeFileSync(new URL('../docs/assets/gallery/index.html', import.meta.url), html);
console.log('wrote docs/assets/gallery/index.html');
