/**
 * SPEC-16 — bundle the interactive demonstrator into a single self-contained
 * page (docs/assets/app/index.html). esbuild inlines the fixtures (imported as
 * JSON modules) and every module, so the artifact has no external dependency —
 * it runs offline from a static host (GitHub Pages) and satisfies the comms
 * §6.2 rule-4 embed shape. The bundle runs the REAL services in the browser
 * (crypto.subtle is the one hash path for Node and the browser); no compute is
 * faked and no downstream is precomputed.
 *
 * Framework-free by design (research note 05 §1): the only build-time dep is
 * esbuild; the runtime is vanilla TS + DOM.
 */
import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

const result = await build({
  entryPoints: [new URL('../src/app/bootstrap.ts', import.meta.url).pathname],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  loader: { '.json': 'json' },
  write: false,
  logLevel: 'info',
});

const js = result.outputFiles[0]!.text;

const html = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-app.ts (npm run build:app) — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ASSAY — the seam, live (SPEC-16)</title>
<style>body{margin:0;background:#EDF0F2}</style>
</head>
<body>
<div id="app"></div>
<script>${js}</script>
</body>
</html>
`;

const outDir = new URL('../docs/assets/app/', import.meta.url);
mkdirSync(outDir, { recursive: true });
writeFileSync(new URL('index.html', outDir), html);
console.log('wrote docs/assets/app/index.html');
