/**
 * SPEC-19 — bundle the spatial/temporal COA mockup into one self-contained page
 * (docs/assets/coa-viz/index.html). esbuild inlines the fixtures and every src
 * module, so the artifact is offline-clean (comms §6 rule 4) while running the
 * REAL in-browser pipeline: a waypoint drag authors a new Plan version and
 * re-scores through the shipped ScoreService — no faked compute, no
 * precomputed downstream (DEC-4).
 *
 * The page is the artefact research note 10's review invitation points at
 * (US1/US3): it carries the two review questions, the Meridian disclaimer, and
 * a frozen date. Page chrome is dark-mode aware; the components themselves ship
 * their own light styling (the SPEC-14 gallery convention).
 */
import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

const FROZEN_DATE = '2026-07-15';

const result = await build({
  entryPoints: [new URL('../src/app/coaVizBootstrap.ts', import.meta.url).pathname],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  loader: { '.json': 'json' },
  write: false,
  logLevel: 'info',
});

const js = result.outputFiles[0]!.text;

const html = `<!DOCTYPE html>
<!-- GENERATED by scripts/build-coa-viz.ts (npm run coa-viz) — do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ASSAY — where the plan meets the water (SPEC-19 mockup, for review)</title>
<style>
:root{color-scheme:light dark;--page:#EDF0F2;--page-ink:#1B2732;--page-muted:#5B6B77;--page-line:#D8DFE4;--accent:#3E5D8A}
@media (prefers-color-scheme: dark){:root{--page:#111820;--page-ink:#E8EEF2;--page-muted:#9FB0BC;--page-line:#2C4A6E}}
body{margin:0;background:var(--page);color:var(--page-ink);font-family:system-ui,sans-serif}
.coaviz-head{max-width:1200px;margin:0 auto;padding:24px 24px 0}
.coaviz-head h1{font-size:22px;margin:0}
.coaviz-head .sub{font-size:12.5px;color:var(--page-muted);margin:6px 0 0;line-height:1.6}
.coaviz-head .disclaimer{font-family:ui-monospace,monospace;font-size:11px;color:var(--page-muted);border:1px dashed var(--page-line);border-radius:8px;padding:8px 12px;margin:12px 0 0}
.coaviz-review{max-width:1200px;margin:0 auto;padding:0 24px}
.coaviz-review .box{background:rgba(62,93,138,.08);border:1px solid var(--accent);border-radius:8px;padding:12px 16px;margin:14px 0 0;font-size:13px;line-height:1.6}
.coaviz-review .box b{color:var(--accent)}
.coaviz-foot{max-width:1200px;margin:0 auto;padding:0 24px 40px;font-size:11.5px;color:var(--page-muted)}
.coaviz-foot a{color:var(--accent)}
</style>
</head>
<body>
<div class="coaviz-head">
  <h1>Where the plan meets the water — a COA as a route through a banded surface</h1>
  <p class="sub"><b>SPEC-19 mockup, for review</b> · frozen ${FROZEN_DATE} · research note <code>10-spatial-temporal.md</code> (DEC-11). Every region is its fixture bounding box, every route its stated <code>plans.json</code> legs, every channel value the real compiled world — a projection of fixtures, not a drawing (DEC-4). Dragging a waypoint authors a <b>new plan version</b> and re-scores it through the <b>real in-browser pipeline</b>; what changed glows (G6). No assessed value renders as a single stop anywhere (G2).</p>
  <p class="disclaimer">The Meridian scenario is engineered fiction (DEC-8). Every banded value on this page is an assessment, not a fact; bands are shown as bands — there is no midpoint, no most-likely value, no heat stop standing in for an interval (DEC-15).</p>
</div>
<div class="coaviz-review">
  <div class="box"><b>Reviewers — two questions</b> (research note 10, closing invitation):<br>
  1. <b>Spatial</b> — is the banded-surface treatment (split fill, hatch for band width, exact [lo, hi] on hover, regions first) <i>honest and legible</i>? Can you find the K6→C4 exposure riser in <code>fac_waters</code> and the K7 route-miss (<code>air_defence</code> untouched) without being told?<br>
  2. <b>Temporal</b> — is the window treatment (discrete validity/task extents, the K5→K9 supersession edge, lapse marking, the quoted-not-curved storm peak) <i>honest and legible</i>? Does scrubbing feel like inspecting a compiled world rather than watching an animation assert one?<br>
  Reactions land via the comms §12 listening loop and feed whether this surface hardens (concept §6 item 21(d), held open on purpose).</div>
</div>
<div id="coaviz-root"></div>
<div class="coaviz-foot">Part of the ASSAY demonstrator (reachable from the Home page card) · identifiers are frozen vignette identifiers (K*, C*, FE-*, P*) · self-contained page, no network calls.</div>
<script>${js}</script>
</body>
</html>
`;

const outDir = new URL('../docs/assets/coa-viz/', import.meta.url);
mkdirSync(outDir, { recursive: true });
writeFileSync(new URL('index.html', outDir), html);
console.log('wrote docs/assets/coa-viz/index.html');
